version: "3.7"
services: 
  nginx:  
    build: nginx1.14.2
    container_name: nginx
    working_dir: /www/html
    volumes: 
      - /www/html:/www/html
      - /docker/nginx1.14.2/etc:/etc/nginx
    restart: always
    ports:
      - 80:80
      - 443:443
  php-fpm:
    build: php-fpm7.1.27
    container_name: php-fpm
    working_dir: /www/html
    volumes:
      - /www/html:/www/html
      - /docker/php-fpm7.1.27/etc:/usr/local/etc
    restart: always
    ports:
      - 9000:9000
  mysql:
    image: mysql:5.7.25
    restart: always
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=loginmysql
      - MYSQL_ROOT_HOST=%
    volumes:
      - /docker/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  reids:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - /docker/redis:/data
    ports:
      - 6379:6379
  memcached:
    image: memcached:latest
    container_name: memcached
    restart: always
    ports:
      - 11211:11211
