version: "3.7"
services: 
  nginx:  
    build: nginx1.14.2
    container_name: nginx
    working_dir: /www/html
    networks: 
      - webserver_network
    volumes: 
      - ~/www/html:/www/html
      - ~/www/run:/www/run
      - ~/docker/nginx1.14.2/etc:/etc/nginx
    restart: always
    ports:
      - 80:80
      - 443:443
  mysql:
    image: mysql:5.7.25
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=loginmysql
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
  reids:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass loginredis123.
    volumes:
      - ~/docker/redis:/data
    ports:
      - 6379:6379
  php71:
    image: reg.xthklocal.cn/xthk-library/php:7.1-fpm
    container_name: php71
    restart: always
    working_dir: /www/html 
    networks: 
      - webserver_network
    volumes: 
      - ~/www/html:/www/html
      - ~/www/run:/www/run
      - ~/www/log:/home/logs/fpm
      - ~/docker/php71/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf
  yupao:
    image: registry.cn-beijing.aliyuncs.com/yupao-base/hyperf-debian-php74:dev
    container_name: yupao
    working_dir: /opt/www
    restart: always
    volumes:
      - ~/www/html:/opt/www
    ports:
      - 9701-9710:9701-9710
      - 9500-9570:9500-9570
    tty: true   
    entrypoint: "bash"
    network_mode: bridge
  go:
    image: golang:buster
    container_name: go
    restart: always
    volumes:
      - ~/www/go:/www/go
    working_dir: /www/go
    tty: true
    ports: 
      - 3000-3005:3000-3005
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports: 
      - 15672:15672 #管理端
      - 5672:5672 #server
  es:
    image: elasticsearch:7.14.2
    container_name: es
    tty: true
    ports:
      - 9200:9200
      - 9300:9300
    environment:
     - ES_JAVA_OPTS=-Xms256m -Xmx256m
     - discovery.type=single-node
  logstash:
    image: logstash:7.14.2
    container_name: logstash
    tty: true
    ports:
      - 5044:5601
      - 9600:9600
    volumes:
      - ~/www/logstash:/www/logstash
  kibana:
    image: kibana:7.14.2
    container_name: kibana
    tty: true
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
  cerebro:
    image: lmenezes/cerebro:latest
    container_name: cerebro
    ports:
      - 9001:9001
    environment:
      - CEREBRO_PORT=9001
  consul:
    image: consul:latest
    container_name: consul
    ports:
      - 8500:8500
  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - 2379:2379
      - 2380:2380
  jdk:
    image: openjdk:17-jdk-oraclelinux7
    container_name: java
    working_dir: /www/java
    tty: true
    volumes: 
      - ~/www/java:/www/java
networks:
  webserver_network:
    driver: bridge
    ipam:
      config:
        - subnet: 173.23.7.0/24

