version: "3.7"
services: 
  nginx:  
    build: nginx1.14.2
    container_name: nginx
    working_dir: /www/html
    volumes: 
      - /www/html:/www/html
      - /www/run:/www/run
      - /docker/nginx1.14.2/etc:/etc/nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php71
      - php73
  php71:
    build: php-fpm7.1.27
    container_name: php71
    working_dir: /www/html
    volumes:
      - /www/html:/www/html
      - /www/run:/www/run
      - /docker/php-fpm7.1.27/etc:/usr/local/etc
    restart: always
  php73:
    build: php-fpm7.3.10
    container_name: php73
    working_dir: /www/html
    volumes:
      - /www/html:/www/html
      - /www/run:/www/run
      - /docker/php-fpm7.3.10/etc:/usr/local/etc
    restart: always
    ports:
      - 9511:9511
      - 9512:9512
  mysql:
    image: mysql:5.7.25
    restart: always
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=loginmysql
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
  reids:
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server --requirepass loginredis123.
    volumes:
      - /docker/redis:/data
    ports:
      - 6379:6379
  memcached:
    image: memcached:latest
    container_name: memcached
    restart: always
    ports:
      - 11211:11211
  elasticsearch:
    restart: always
    container_name: es
    image: elasticsearch:2.0
    privileged: true
    volumes:
      - /docker/elasticsearch/config:/usr/share/elasticsearch/config
    environment:
      - cluster.name=docker-cluster  
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
