version: "3.7"
services: 
  nginx:  
    build: nginx1.14.2
    container_name: nginx
    working_dir: /www/html
    volumes: 
      - /www/html:/www/html
      - /www/run:/www/run
      - /docker/nginx1.14.2/etc:/etc/nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php73
  php73:
    build: php-fpm7.3.10
    container_name: php73
    working_dir: /www/html
    volumes:
      - /www/html:/www/html
      - /www/run:/www/run
      - /docker/php-fpm7.3.10/etc:/usr/local/etc
    restart: always
    ports:
      - 9511:9511
      - 9512:9512
      - 9513:9513
      - 9514:9514
      - 9515:9515
  mysql:
    image: mysql:5.7.25
    restart: always
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=loginmysql
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
  reids:
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server --requirepass loginredis123.
    volumes:
      - /docker/redis:/data
    ports:
      - 6379:6379
  memcached:
    image: memcached:latest
    container_name: memcached
    restart: always
    ports:
      - 11211:11211
  elasticsearch:
    image: elasticsearch:7.9.0
    container_name: es
    restart: always
    volumes:
      - /docker/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - cluster.name=elasticsearch
      - discovery.type=single-node
      - node.name=es7_01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: kibana:7.9.0
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    restart: always
